name: Build and Release

on:
  push:
    branches: [ master, release ]
  pull_request:
    branches: [ master, release ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: brightness-widget
        path: dist/brightness-widget.exe
        
  release:
    needs: build
    if: github.ref == 'refs/heads/release'
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: brightness-widget
        path: dist
    
    - name: Get version from package.json
      id: get_version
      run: |
        $version = (Get-Content package.json | ConvertFrom-Json).version
        echo "version=$version" >> $env:GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: v${{ steps.get_version.outputs.version }}
        tag_name: v${{ steps.get_version.outputs.version }}
        files: |
          dist/brightness-widget.exe
        draft: false
        prerelease: false
